version: '2'

services:

  mongo:
    image: mongo
    restart: on-failure
    env_file: 
      - ./.env
    volumes:
      - ./data:/data/db

  # mongo-express:
  #   image: mongo-express
  #   restart: on-failure
  #   links:
  #     - mongo
  #   ports:
  #     - 8081:8081
  #   env_file: 
  #     - ./.env

  api:
    image: node:10-alpine
    restart: on-failure
    links:
      - mongo
    env_file: 
      - ./.env
    volumes:
      - ./server:/usr/src/app
      - ./files:/etc/server_files
    working_dir: /usr/src/app
    entrypoint: node ./bin/www
    # entrypoint: npm run dev

  web:
    image: nginx:alpine
    restart: on-failure
    links:
      - api
    ports:
      - 8080:80
    env_file: 
      - ./.env
    volumes:
      - ./client/dist:/usr/share/nginx/html:ro
      - ./client/conf.d:/etc/nginx/conf.d:ro
